changelog:
  categories:
    - title: "Funktionen"
      labels:
        - "feature"
        - "enhancement"
    - title: "Fehlerbehebungen"
      labels:
        - "bug"
        - "fix"
    - title: "Wartung"
      labels:
        - "chore"
        - "docs"
        - "refactor"
  exclude:
    labels:
      - "skip-changelog"
