changelog:
  categories:
    - title: "Features"
      labels:
        - "feature"
        - "enhancement"
    - title: "Fixes"
      labels:
        - "bug"
        - "fix"
    - title: "Maintenance"
      labels:
        - "chore"
        - "docs"
        - "refactor"
  exclude:
    labels:
      - "skip-changelog"
